### PR TITLE
Add support for wofi

### PR DESCRIPTION
**Pull request by luispabon**
Wofi is a wayland native, rofi analog:

https://hg.sr.ht/~scoopta/wofi

This adds support for it.
image

### CODE REVIEW

**Comment by yory8** [comment]
Thank'you! I wasn't aware it existed, I'll probably switch to it too =D

**Comment by luispabon** [comment]
It's pretty new, I've been using it as a substitute for a few rofi things and it's still a little buggy and rough in places, but works great and uses layer-shell

**Comment by yory8** [comment]
Note that I pushed a new commit that disables wofi's cache -- it's not meant for our user case, but for when running it as an application launcher

**Comment by luispabon** [comment]
One thing I've just come across while I was styling wofi is that errors on styles generate gtk warnings on the output, mangling the clean output clipman is expecting:

```
(wofi:11490): Gtk-WARNING **: 15:45:40.271: Theme parsing error: <data>:15:14: Not using units is deprecated. Assuming 'px'.
Stuff
```
`Stuff` is the selection.

I'm not sure how to get around this without custom code in clipman that would muddy your codebase.

**Comment by yory8** [comment]
We should see whether they are both sent to stdout, or the gtk stuff goes to stderr

**Comment by yory8** [comment]
Fixed. Ignoring stderr seems to do the trick, and doesn't seem to affect dmenu users.

**Comment by luispabon** [comment]
Perfecto 👌

**Pull request merged**
